environment:
  type: TerraShift
  params:
    # Core environment params
    PlatformSize: 1.0
    MaxColumnHeight: 2.0
    ObjectSize: [0.10, 0.10, 0.10]
    ObjectMass: 1.0
    GridSize: 50
    MaxSteps: 512
    NumGoals: 4
    SpawnDelay: 1.0
    RespawnDelay: 1.0
    MaxAgents: 10
    GoalThreshold: 0.2

    # Discrete 2D Fourier parameter(s)
    # Only MatrixDeltaRange remains
    MatrixDeltaRange: [-1.5, 1.5]
    K: 8  # number of fundamental modes => (2K x 2K) matrix per agent

  shape:
    is_multi_agent: True
    # single_agent_obs_size = 2 + (2*K x 2*K) + 26
    # If K=8 => (2 + 16*16) + 26 = 284
    single_agent_obs_size: 284
    max_agents: 10

    action_space:
      type: discrete
      # Each agent has 2 discrete actions:
      # 0 -> direction (Up=0, Down=1, Left=2, Right=3) => 4 choices
      # 1 -> partial update (Inc=0, Dec=1, Zero=2, None=3) => 4 choices
      agent_actions:
        - num_choices: 4
        - num_choices: 4

agent:
  type: MA_POCA
  params:
    learning_rate: 0.0002
    gamma: 0.99
    lambda: 0.95
    hidden_size: 256
    normalize_rewards: False
    normalize_advantages: False
    value_loss_coeff: 1.0
    baseline_loss_coeff: 1.0
    max_grad_norm: 1.0
    ppo_clip_range: 0.1

    target_entropy: -8.0
    entropy_lambda_lr: 0.0003
    entropy_lambda_initial: 0.0
    entropy_coeff: 0.1

    schedulers:
      lr:
        start_factor: 1.0
        end_factor: 0.001
        total_iters: 50000
      entropy_coeff:
        start_value: 0.1
        end_value: 0.0001
        total_iters: 50000
    networks:
      policy_network:
        in_features: 256
        hidden_size: 256

      critic_network:
        value_head:
          in_features: 256
          hidden_size: 256
          dropout_rate: 0.0
        baseline_head:
          in_features: 256
          hidden_size: 256
          dropout_rate: 0.0
          
      MultiAgentEmbeddingNetwork:
        general_obs_encoder:
          input_size: 284       # total dimension of the agent's observation
          output_size: 256      # final dimension after concatenating sub-encoders & feeding aggregator FC

          sub_encoders:
            - name: "SpatialPart"
              network: "SpatialNetwork2D"
              params:
                h: 16
                w: 16
                in_channels: 1
                out_channels: 8
                kernel_size: 3
                stride: 1
                padding: 1
              slice: [0, 255]    # covers 256 elements of the obs
              out_features: 2048 # since 8 x 16 x 16 = 2048 after flattening

            - name: "LinearPart"
              network: "LinearNetwork"
              params:
                in_features: 28     # for slice [256..283] => 28 elements
                out_features: 128
                dropout_rate: 0.0
                activation: True
              slice: [256, 283]     # covers the last 28 elements
              out_features: 128

        agent_id_enc:
          num_freqs: 64
          id_embed_dim: 256

        RSA:
          embed_size: 256
          heads: 8
          dropout_rate: 0.0

        agent_obs_encoder:
          state_dim: 256
          output_size: 256
          dropout_rate: 0.0
          activation: True

        obs_actions_encoder:
          state_dim: 256
          action_dim: 2
          output_size: 256
          dropout_rate: 0.0
          activation: True
train:
  normalize_states: True
  num_environments: 1
  epochs: 3
  mini_batch_size: 8
  buffer_size: 128
  batch_size: 128
  AgentsResetFrequency: 0
  ActionRepeat: 0
  saveFrequency: 20
